#! /bin/sh
### BEGIN INIT INFO
# Provides:          mvml-host-server
# Required-Start:
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: an mvml hosting server
# Description:       a server for editing and hosting mvml
### END INIT INFO

DIR=/home/JScott/prod/mvml-host/
SCRIPT=server.js

case "$1" in
	start)
		cd ${DIR}
		sudo node ${SCRIPT} &
		;;
	stop)
		sudo pkill -f "node ${SCRIPT}"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
