#!/bin/bash
NAME='mvml-host'
DIR="/home/JScott/prod/${NAME}/"
SCRIPT='server.js'
LOG_FILE="/data/log/${NAME}.log"
PID_FILE="/var/run/${NAME}.pid"
COMMAND="node ${DIR}${SCRIPT} 80"

start() {
    ${COMMAND} 1>${LOG_FILE} 2>&1 &
    echo $! > ${PID_FILE}
}

stop() {
    kill `cat ${PID_FILE}`
    rm ${PID_FILE}
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit $?
